version: '3.6'
services:
  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    # restart: always
    volumes:
     - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node    
    ports:
     - '9200:9200'
     - '9300:9300'
    networks:
      - elk

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    ports:
      - 1433:1433
    volumes:
      - ./jdbc:/jdbc 
    networks:
      - elk

  Logstash:
    image: logstash:7.16.2
    container_name: logstash
    # restart: always
    volumes:
      - ./logstash/:/logstash_dir
      - ./jdbc:/jdbc
    command: logstash -f /logstash_dir/beatsTologstash.config
    depends_on:
      - Elasticsearch
      - sqlserver
    ports:
      - '9600:9600' 
    environment:
       LOGSTASH_JDBC_DRIVER: com.microsoft.sqlserver.jdbc.SQLServerDriver
       LOGSTASH_JDBC_CONNECTION_STRING: 'jdbc:sqlserver://sqlserver:1433;databaseName=elasticTest;encrypt=false;trustServerCertificate=true'
       LOGSTASH_JDBC_USER: sa
       LOGSTASH_JDBC_PASSWORD: P@ssw0rd  
    networks:
      - elk

  Kibana:
    image: kibana:7.16.2
    container_name: kibana
    # restart: always       
    ports:
    - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  
    depends_on:
      - Elasticsearch  
    networks:
      - elk
  filebeat:
    image : docker.elastic.co/beats/filebeat:7.16.2
    container_name: filebeatLogs
    depends_on:
      - Logstash
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/usr/share/filebeat/logs
    user: root
    command: filebeat -e  -c  /usr/share/filebeat/filebeat.yml
    networks:
       - elk 
volumes:
  elastic_data: {}

networks:
  elk: